use debug_et_diagnostics::{invert_ansi, from_byte};

#[test]
fn test_invert_ansi() {
    assert_eq!(invert_ansi(from_byte(0).into()), 231);
    assert_eq!(invert_ansi(from_byte(1).into()), 35);
    assert_eq!(invert_ansi(from_byte(2).into()), 35);
    assert_eq!(invert_ansi(from_byte(3).into()), 231);
    assert_eq!(invert_ansi(from_byte(4).into()), 250);
    assert_eq!(invert_ansi(from_byte(5).into()), 231);
    assert_eq!(invert_ansi(from_byte(6).into()), 231);
    assert_eq!(invert_ansi(from_byte(7).into()), 17);
    assert_eq!(invert_ansi(from_byte(8).into()), 83);
    assert_eq!(invert_ansi(from_byte(9).into()), 231);
    assert_eq!(invert_ansi(from_byte(10).into()), 231);
    assert_eq!(invert_ansi(from_byte(11).into()), 231);
    assert_eq!(invert_ansi(from_byte(12).into()), 231);
    assert_eq!(invert_ansi(from_byte(13).into()), 231);
    assert_eq!(invert_ansi(from_byte(14).into()), 231);
    assert_eq!(invert_ansi(from_byte(15).into()), 231);
    assert_eq!(invert_ansi(from_byte(16).into()), 231);
    assert_eq!(invert_ansi(from_byte(17).into()), 109);
    assert_eq!(invert_ansi(from_byte(18).into()), 70);
    assert_eq!(invert_ansi(from_byte(19).into()), 65);
    assert_eq!(invert_ansi(from_byte(20).into()), 25);
    assert_eq!(invert_ansi(from_byte(21).into()), 231);
    assert_eq!(invert_ansi(from_byte(22).into()), 109);
    assert_eq!(invert_ansi(from_byte(23).into()), 231);
    assert_eq!(invert_ansi(from_byte(24).into()), 24);
    assert_eq!(invert_ansi(from_byte(25).into()), 248);
    assert_eq!(invert_ansi(from_byte(26).into()), 69);
    assert_eq!(invert_ansi(from_byte(27).into()), 87);
    assert_eq!(invert_ansi(from_byte(28).into()), 70);
    assert_eq!(invert_ansi(from_byte(29).into()), 24);
    assert_eq!(invert_ansi(from_byte(30).into()), 231);
    assert_eq!(invert_ansi(from_byte(31).into()), 207);
    assert_eq!(invert_ansi(from_byte(32).into()), 131);
    assert_eq!(invert_ansi(from_byte(33).into()), 90);
    assert_eq!(invert_ansi(from_byte(34).into()), 65);
    assert_eq!(invert_ansi(from_byte(35).into()), 248);
    assert_eq!(invert_ansi(from_byte(36).into()), 207);
    assert_eq!(invert_ansi(from_byte(37).into()), 231);
    assert_eq!(invert_ansi(from_byte(38).into()), 90);
    assert_eq!(invert_ansi(from_byte(39).into()), 131);
    assert_eq!(invert_ansi(from_byte(40).into()), 25);
    assert_eq!(invert_ansi(from_byte(41).into()), 69);
    assert_eq!(invert_ansi(from_byte(42).into()), 131);
    assert_eq!(invert_ansi(from_byte(43).into()), 90);
    assert_eq!(invert_ansi(from_byte(44).into()), 231);
    assert_eq!(invert_ansi(from_byte(45).into()), 207);
    assert_eq!(invert_ansi(from_byte(46).into()), 231);
    assert_eq!(invert_ansi(from_byte(47).into()), 87);
    assert_eq!(invert_ansi(from_byte(48).into()), 90);
    assert_eq!(invert_ansi(from_byte(49).into()), 131);
    assert_eq!(invert_ansi(from_byte(50).into()), 207);
    assert_eq!(invert_ansi(from_byte(51).into()), 231);
    assert_eq!(invert_ansi(from_byte(52).into()), 109);
    assert_eq!(invert_ansi(from_byte(53).into()), 231);
    assert_eq!(invert_ansi(from_byte(54).into()), 24);
    assert_eq!(invert_ansi(from_byte(55).into()), 248);
    assert_eq!(invert_ansi(from_byte(56).into()), 69);
    assert_eq!(invert_ansi(from_byte(57).into()), 87);
    assert_eq!(invert_ansi(from_byte(58).into()), 231);
    assert_eq!(invert_ansi(from_byte(59).into()), 109);
    assert_eq!(invert_ansi(from_byte(60).into()), 70);
    assert_eq!(invert_ansi(from_byte(61).into()), 65);
    assert_eq!(invert_ansi(from_byte(62).into()), 25);
    assert_eq!(invert_ansi(from_byte(63).into()), 231);
    assert_eq!(invert_ansi(from_byte(64).into()), 24);
    assert_eq!(invert_ansi(from_byte(65).into()), 70);
    assert_eq!(invert_ansi(from_byte(66).into()), 109);
    assert_eq!(invert_ansi(from_byte(67).into()), 91);
    assert_eq!(invert_ansi(from_byte(68).into()), 16);
    assert_eq!(invert_ansi(from_byte(69).into()), 202);
    assert_eq!(invert_ansi(from_byte(70).into()), 248);
    assert_eq!(invert_ansi(from_byte(71).into()), 65);
    assert_eq!(invert_ansi(from_byte(72).into()), 91);
    assert_eq!(invert_ansi(from_byte(73).into()), 109);
    assert_eq!(invert_ansi(from_byte(74).into()), 202);
    assert_eq!(invert_ansi(from_byte(75).into()), 16);
    assert_eq!(invert_ansi(from_byte(76).into()), 69);
    assert_eq!(invert_ansi(from_byte(77).into()), 25);
    assert_eq!(invert_ansi(from_byte(78).into()), 16);
    assert_eq!(invert_ansi(from_byte(79).into()), 202);
    assert_eq!(invert_ansi(from_byte(80).into()), 109);
    assert_eq!(invert_ansi(from_byte(81).into()), 91);
    assert_eq!(invert_ansi(from_byte(82).into()), 87);
    assert_eq!(invert_ansi(from_byte(83).into()), 231);
    assert_eq!(invert_ansi(from_byte(84).into()), 202);
    assert_eq!(invert_ansi(from_byte(85).into()), 16);
    assert_eq!(invert_ansi(from_byte(86).into()), 91);
    assert_eq!(invert_ansi(from_byte(87).into()), 109);
    assert_eq!(invert_ansi(from_byte(88).into()), 70);
    assert_eq!(invert_ansi(from_byte(89).into()), 24);
    assert_eq!(invert_ansi(from_byte(90).into()), 231);
    assert_eq!(invert_ansi(from_byte(91).into()), 207);
    assert_eq!(invert_ansi(from_byte(92).into()), 131);
    assert_eq!(invert_ansi(from_byte(93).into()), 90);
    assert_eq!(invert_ansi(from_byte(94).into()), 24);
    assert_eq!(invert_ansi(from_byte(95).into()), 70);
    assert_eq!(invert_ansi(from_byte(96).into()), 109);
    assert_eq!(invert_ansi(from_byte(97).into()), 91);
    assert_eq!(invert_ansi(from_byte(98).into()), 16);
    assert_eq!(invert_ansi(from_byte(99).into()), 202);
    assert_eq!(invert_ansi(from_byte(100).into()), 231);
    assert_eq!(invert_ansi(from_byte(101).into()), 0);
    // assert_eq!(invert_ansi(from_byte(102).into()), 0);
    // assert_eq!(invert_ansi(from_byte(103).into()), 0);
    // assert_eq!(invert_ansi(from_byte(104).into()), 0);
    // assert_eq!(invert_ansi(from_byte(105).into()), 0);
    // assert_eq!(invert_ansi(from_byte(106).into()), 0);
    // assert_eq!(invert_ansi(from_byte(107).into()), 0);
    // assert_eq!(invert_ansi(from_byte(108).into()), 0);
    // assert_eq!(invert_ansi(from_byte(109).into()), 0);
    // assert_eq!(invert_ansi(from_byte(110).into()), 0);
    // assert_eq!(invert_ansi(from_byte(111).into()), 0);
    // assert_eq!(invert_ansi(from_byte(112).into()), 0);
    // assert_eq!(invert_ansi(from_byte(113).into()), 0);
    // assert_eq!(invert_ansi(from_byte(114).into()), 0);
    // assert_eq!(invert_ansi(from_byte(115).into()), 0);
    // assert_eq!(invert_ansi(from_byte(116).into()), 0);
    // assert_eq!(invert_ansi(from_byte(117).into()), 0);
    // assert_eq!(invert_ansi(from_byte(118).into()), 0);
    // assert_eq!(invert_ansi(from_byte(119).into()), 0);
    // assert_eq!(invert_ansi(from_byte(120).into()), 0);
    // assert_eq!(invert_ansi(from_byte(121).into()), 0);
    // assert_eq!(invert_ansi(from_byte(122).into()), 0);
    // assert_eq!(invert_ansi(from_byte(123).into()), 0);
    // assert_eq!(invert_ansi(from_byte(124).into()), 0);
    // assert_eq!(invert_ansi(from_byte(125).into()), 0);
    // assert_eq!(invert_ansi(from_byte(126).into()), 0);
    // assert_eq!(invert_ansi(from_byte(127).into()), 0);
    // assert_eq!(invert_ansi(from_byte(128).into()), 0);
    // assert_eq!(invert_ansi(from_byte(129).into()), 0);
    // assert_eq!(invert_ansi(from_byte(130).into()), 0);
    // assert_eq!(invert_ansi(from_byte(131).into()), 0);
    // assert_eq!(invert_ansi(from_byte(132).into()), 0);
    // assert_eq!(invert_ansi(from_byte(133).into()), 0);
    // assert_eq!(invert_ansi(from_byte(134).into()), 0);
    // assert_eq!(invert_ansi(from_byte(135).into()), 0);
    // assert_eq!(invert_ansi(from_byte(136).into()), 0);
    // assert_eq!(invert_ansi(from_byte(137).into()), 0);
    // assert_eq!(invert_ansi(from_byte(138).into()), 0);
    // assert_eq!(invert_ansi(from_byte(139).into()), 0);
    // assert_eq!(invert_ansi(from_byte(140).into()), 0);
    // assert_eq!(invert_ansi(from_byte(141).into()), 0);
    // assert_eq!(invert_ansi(from_byte(142).into()), 0);
    // assert_eq!(invert_ansi(from_byte(143).into()), 0);
    // assert_eq!(invert_ansi(from_byte(144).into()), 0);
    // assert_eq!(invert_ansi(from_byte(145).into()), 0);
    // assert_eq!(invert_ansi(from_byte(146).into()), 0);
    // assert_eq!(invert_ansi(from_byte(147).into()), 0);
    // assert_eq!(invert_ansi(from_byte(148).into()), 0);
    // assert_eq!(invert_ansi(from_byte(149).into()), 0);
    // assert_eq!(invert_ansi(from_byte(150).into()), 0);
    // assert_eq!(invert_ansi(from_byte(151).into()), 0);
    // assert_eq!(invert_ansi(from_byte(152).into()), 0);
    // assert_eq!(invert_ansi(from_byte(153).into()), 0);
    // assert_eq!(invert_ansi(from_byte(154).into()), 0);
    // assert_eq!(invert_ansi(from_byte(155).into()), 0);
    // assert_eq!(invert_ansi(from_byte(156).into()), 0);
    // assert_eq!(invert_ansi(from_byte(157).into()), 0);
    // assert_eq!(invert_ansi(from_byte(158).into()), 0);
    // assert_eq!(invert_ansi(from_byte(159).into()), 0);
    // assert_eq!(invert_ansi(from_byte(160).into()), 0);
    // assert_eq!(invert_ansi(from_byte(161).into()), 0);
    // assert_eq!(invert_ansi(from_byte(162).into()), 0);
    // assert_eq!(invert_ansi(from_byte(163).into()), 0);
    // assert_eq!(invert_ansi(from_byte(164).into()), 0);
    // assert_eq!(invert_ansi(from_byte(165).into()), 0);
    // assert_eq!(invert_ansi(from_byte(166).into()), 0);
    // assert_eq!(invert_ansi(from_byte(167).into()), 0);
    // assert_eq!(invert_ansi(from_byte(168).into()), 0);
    // assert_eq!(invert_ansi(from_byte(169).into()), 0);
    // assert_eq!(invert_ansi(from_byte(170).into()), 0);
    // assert_eq!(invert_ansi(from_byte(171).into()), 0);
    // assert_eq!(invert_ansi(from_byte(172).into()), 0);
    // assert_eq!(invert_ansi(from_byte(173).into()), 0);
    // assert_eq!(invert_ansi(from_byte(174).into()), 0);
    // assert_eq!(invert_ansi(from_byte(175).into()), 0);
    // assert_eq!(invert_ansi(from_byte(176).into()), 0);
    // assert_eq!(invert_ansi(from_byte(177).into()), 0);
    // assert_eq!(invert_ansi(from_byte(178).into()), 0);
    // assert_eq!(invert_ansi(from_byte(179).into()), 0);
    // assert_eq!(invert_ansi(from_byte(180).into()), 0);
    // assert_eq!(invert_ansi(from_byte(181).into()), 0);
    // assert_eq!(invert_ansi(from_byte(182).into()), 0);
    // assert_eq!(invert_ansi(from_byte(183).into()), 0);
    // assert_eq!(invert_ansi(from_byte(184).into()), 0);
    // assert_eq!(invert_ansi(from_byte(185).into()), 0);
    // assert_eq!(invert_ansi(from_byte(186).into()), 0);
    // assert_eq!(invert_ansi(from_byte(187).into()), 0);
    // assert_eq!(invert_ansi(from_byte(188).into()), 0);
    // assert_eq!(invert_ansi(from_byte(189).into()), 0);
    // assert_eq!(invert_ansi(from_byte(190).into()), 0);
    // assert_eq!(invert_ansi(from_byte(191).into()), 0);
    // assert_eq!(invert_ansi(from_byte(192).into()), 0);
    // assert_eq!(invert_ansi(from_byte(193).into()), 0);
    // assert_eq!(invert_ansi(from_byte(194).into()), 0);
    // assert_eq!(invert_ansi(from_byte(195).into()), 0);
    // assert_eq!(invert_ansi(from_byte(196).into()), 0);
    // assert_eq!(invert_ansi(from_byte(197).into()), 0);
    // assert_eq!(invert_ansi(from_byte(198).into()), 0);
    // assert_eq!(invert_ansi(from_byte(199).into()), 0);
    // assert_eq!(invert_ansi(from_byte(200).into()), 0);
    // assert_eq!(invert_ansi(from_byte(201).into()), 0);
    // assert_eq!(invert_ansi(from_byte(202).into()), 0);
    // assert_eq!(invert_ansi(from_byte(203).into()), 0);
    // assert_eq!(invert_ansi(from_byte(204).into()), 0);
    // assert_eq!(invert_ansi(from_byte(205).into()), 0);
    // assert_eq!(invert_ansi(from_byte(206).into()), 0);
    // assert_eq!(invert_ansi(from_byte(207).into()), 0);
    // assert_eq!(invert_ansi(from_byte(208).into()), 0);
    // assert_eq!(invert_ansi(from_byte(209).into()), 0);
    // assert_eq!(invert_ansi(from_byte(210).into()), 0);
    // assert_eq!(invert_ansi(from_byte(211).into()), 0);
    // assert_eq!(invert_ansi(from_byte(212).into()), 0);
    // assert_eq!(invert_ansi(from_byte(213).into()), 0);
    // assert_eq!(invert_ansi(from_byte(214).into()), 0);
    // assert_eq!(invert_ansi(from_byte(215).into()), 0);
    // assert_eq!(invert_ansi(from_byte(216).into()), 0);
    // assert_eq!(invert_ansi(from_byte(217).into()), 0);
    // assert_eq!(invert_ansi(from_byte(218).into()), 0);
    // assert_eq!(invert_ansi(from_byte(219).into()), 0);
    // assert_eq!(invert_ansi(from_byte(220).into()), 0);
    // assert_eq!(invert_ansi(from_byte(221).into()), 0);
    // assert_eq!(invert_ansi(from_byte(222).into()), 0);
    // assert_eq!(invert_ansi(from_byte(223).into()), 0);
    // assert_eq!(invert_ansi(from_byte(224).into()), 0);
    // assert_eq!(invert_ansi(from_byte(225).into()), 0);
    // assert_eq!(invert_ansi(from_byte(226).into()), 0);
    // assert_eq!(invert_ansi(from_byte(227).into()), 0);
    // assert_eq!(invert_ansi(from_byte(228).into()), 0);
    // assert_eq!(invert_ansi(from_byte(229).into()), 0);
    // assert_eq!(invert_ansi(from_byte(230).into()), 0);
    // assert_eq!(invert_ansi(from_byte(231).into()), 0);
    // assert_eq!(invert_ansi(from_byte(232).into()), 0);
    // assert_eq!(invert_ansi(from_byte(233).into()), 0);
    // assert_eq!(invert_ansi(from_byte(234).into()), 0);
    // assert_eq!(invert_ansi(from_byte(235).into()), 0);
    // assert_eq!(invert_ansi(from_byte(236).into()), 0);
    // assert_eq!(invert_ansi(from_byte(237).into()), 0);
    // assert_eq!(invert_ansi(from_byte(238).into()), 0);
    // assert_eq!(invert_ansi(from_byte(239).into()), 0);
    // assert_eq!(invert_ansi(from_byte(240).into()), 0);
    // assert_eq!(invert_ansi(from_byte(241).into()), 0);
    // assert_eq!(invert_ansi(from_byte(242).into()), 0);
    // assert_eq!(invert_ansi(from_byte(243).into()), 0);
    // assert_eq!(invert_ansi(from_byte(244).into()), 0);
    // assert_eq!(invert_ansi(from_byte(245).into()), 0);
    // assert_eq!(invert_ansi(from_byte(246).into()), 0);
    // assert_eq!(invert_ansi(from_byte(247).into()), 0);
    // assert_eq!(invert_ansi(from_byte(248).into()), 0);
    // assert_eq!(invert_ansi(from_byte(249).into()), 0);
    // assert_eq!(invert_ansi(from_byte(250).into()), 0);
    // assert_eq!(invert_ansi(from_byte(251).into()), 0);
    // assert_eq!(invert_ansi(from_byte(252).into()), 0);
    // assert_eq!(invert_ansi(from_byte(253).into()), 0);
    // assert_eq!(invert_ansi(from_byte(254).into()), 0);
    // assert_eq!(invert_ansi(from_byte(255).into()), 0);
}
